require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "lib/**/*"
    - "spec/**/*"
    - "config/**/*"
    - "node_modules/**/*"
    - "Gemfile"
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 100

Layout/ArgumentAlignment:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

I18nLocaleTexts:
  Enabled: false